server:
  http_listen_port: 9080
  grpc_listen_port: 0

# include position in production, for now it is ignored
# positions:
#   filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      # keep only containers that match your service names
      - source_labels: ['__meta_docker_container_name']
        regex: '/letslive-(auth|user|livestream|transcode|chat).*'
        action: keep

      # clean up container name (remove leading slash)
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'

      # label by stdout/stderr stream
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'

      # make "job" label equal to container name
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'job'

